from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class PersonaLibraryDefinition:
    key: str
    category: str
    label: str
    purpose: str
    extraction_targets: tuple[str, ...]
    retrieval_triggers: tuple[str, ...]
    prompt_budget: int = 220
    default_usage: str = "retrieval_snippet"


def _lib(
    key: str,
    category: str,
    label: str,
    purpose: str,
    extraction_targets: tuple[str, ...],
    retrieval_triggers: tuple[str, ...],
    prompt_budget: int = 220,
) -> PersonaLibraryDefinition:
    return PersonaLibraryDefinition(
        key=key,
        category=category,
        label=label,
        purpose=purpose,
        extraction_targets=extraction_targets,
        retrieval_triggers=retrieval_triggers,
        prompt_budget=prompt_budget,
    )


PERSONA_LIBRARY_REGISTRY: tuple[PersonaLibraryDefinition, ...] = (
    _lib(
        "fact_life_events",
        "fact_memory",
        "生平经历库",
        "保存可被证据支持的人生阶段、重要事件和经历变化。",
        ("时间", "事件", "地点", "参与人物", "证据原文", "置信度"),
        ("用户问事实", "用户问过去经历", "需要确认是否能引用经历"),
    ),
    _lib(
        "fact_shared_memories",
        "fact_memory",
        "共同经历库",
        "保存用户和目标人物之间被证据确认的共同经历。",
        ("共同事件", "双方关系", "发生时间", "证据原文", "是否可直接引用"),
        ("用户提到一起经历", "用户问还记不记得", "聊天需要引用共同记忆"),
    ),
    _lib(
        "fact_people",
        "fact_memory",
        "重要人物库",
        "保存目标人物关系网中的重要人物和关系强度。",
        ("人物名称", "关系", "态度", "证据原文", "冲突信息"),
        ("用户提到家人朋友", "需要判断关系距离", "事实问答"),
    ),
    _lib(
        "fact_places",
        "fact_memory",
        "重要地点库",
        "保存地点、场所、生活环境和可引用的空间记忆。",
        ("地点", "场景", "相关人物", "情绪色彩", "证据原文"),
        ("用户提到地点", "需要引用场景", "怀念或回忆类输入"),
    ),
    _lib(
        "fact_timeline",
        "fact_memory",
        "时间线库",
        "保存事件顺序、时期差异和资料来源时间段。",
        ("时间点", "先后顺序", "时期标签", "证据来源", "不确定性"),
        ("用户问什么时候", "需要区分年轻时/后来", "成长变化判断"),
    ),
    _lib(
        "fact_habits",
        "fact_memory",
        "生活习惯事实库",
        "保存作息、饮食、偏好、固定动作等事实性习惯。",
        ("习惯", "频率", "场景", "证据原文", "可引用范围"),
        ("日常问候", "照顾提醒", "用户问生活习惯"),
    ),
    _lib(
        "fact_direct_quotes",
        "fact_memory",
        "原话证据库",
        "保存可追溯的直接原话，供风格和事实判断引用。",
        ("原话", "说话场景", "对象", "语气", "来源"),
        ("需要引用原话", "语言风格分析", "高置信模仿"),
    ),
    _lib(
        "fact_uncertain_claims",
        "fact_memory",
        "低置信传闻库",
        "保存无法确认、冲突或只出现一次的事实候选。",
        ("候选事实", "不确定原因", "冲突证据", "来源", "禁用范围"),
        ("用户追问不确定事实", "事实边界检查", "低样本降级"),
    ),
    _lib(
        "language_vocabulary",
        "language_style",
        "常用词库",
        "保存高频词、偏好用词和有个人辨识度的词汇。",
        ("词语", "出现频率", "语境", "替代表达", "禁用条件"),
        ("普通聊天", "语言风格生成", "用户要求像一点"),
    ),
    _lib(
        "language_catchphrases",
        "language_style",
        "口头禅库",
        "保存稳定短句、重复句和强风格原话。",
        ("短句", "场景", "强度", "可复用程度", "机械复读风险"),
        ("日常回应", "安抚", "提醒", "风格增强"),
    ),
    _lib(
        "language_address_terms",
        "language_style",
        "称呼习惯库",
        "保存称呼、昵称、省略称呼和亲密距离。",
        ("称呼", "对象", "关系", "亲密度", "禁用条件"),
        ("开头称呼", "关系判断", "亲密表达"),
    ),
    _lib(
        "language_particles",
        "language_style",
        "语气词库",
        "保存嗯、啊、吧、呢、好了、行了等语气标记。",
        ("语气词", "位置", "情绪", "使用频率", "过度使用风险"),
        ("短句生成", "低落安抚", "日常聊天"),
    ),
    _lib(
        "language_punctuation",
        "language_style",
        "标点停顿库",
        "保存逗号、句号、省略号、感叹号等停顿方式。",
        ("标点", "停顿含义", "句内位置", "节奏效果", "反例"),
        ("控制回复节奏", "断句生成", "避免长篇"),
    ),
    _lib(
        "language_symbols",
        "language_style",
        "表情符号库",
        "保存 emoji、颜文字、括号补充、波浪号等符号习惯。",
        ("符号", "使用场景", "情绪强度", "频率", "禁用条件"),
        ("轻松聊天", "玩笑", "年轻化表达判断"),
    ),
    _lib(
        "language_sentence_break",
        "language_style",
        "断句习惯库",
        "保存短句、半句、换行、先停顿再补充等断句方式。",
        ("断句形态", "例句", "默认句数", "换行倾向", "节奏说明"),
        ("所有聊天回复", "安抚", "提醒", "低样本降级"),
    ),
    _lib(
        "language_sentence_length",
        "language_style",
        "句长与回复长度库",
        "保存一句话长度、一次回复句数和长短文边界。",
        ("字数范围", "句数范围", "长回复条件", "短回复条件", "过长风险"),
        ("所有聊天回复", "成本控制", "避免模型长篇发挥"),
    ),
    _lib(
        "language_word_order",
        "language_style",
        "语序习惯库",
        "保存先安抚/先提醒/先判断/后解释等表达顺序。",
        ("顺序模板", "场景", "例句", "稳定程度", "反例"),
        ("求建议", "低落", "逞强", "冲突"),
    ),
    _lib(
        "language_sentence_forms",
        "language_style",
        "句式类型库",
        "保存陈述句、祈使句、反问句、追问句、否定句偏好。",
        ("句式", "场景", "语气强度", "可用模板", "禁用条件"),
        ("提问", "提醒", "冲突", "安抚"),
    ),
    _lib(
        "language_connectors",
        "language_style",
        "连接结构库",
        "保存先 X 再 Y、别 X 我 Y、如果 X 就 Y 等连接方式。",
        ("连接模板", "例句", "语义作用", "使用场景", "替代表达"),
        ("行动提醒", "建议", "安抚", "解释"),
    ),
    _lib(
        "language_modifier_density",
        "language_style",
        "修饰密度库",
        "保存直白/绕一点/解释多/比喻多/形容词密度等特点。",
        ("修饰强度", "解释密度", "比喻倾向", "直白程度", "反例"),
        ("控制模型展开程度", "价值判断", "长回复"),
    ),
    _lib(
        "language_opening_style",
        "language_style",
        "开头方式库",
        "保存先叫人、先回应情绪、先制止、直接给动作等开场。",
        ("开头类型", "场景", "例句", "亲密度", "风险"),
        ("所有聊天开头", "日常问候", "低落", "逞强"),
    ),
    _lib(
        "language_closing_style",
        "language_style",
        "结尾方式库",
        "保存停在陪伴、停在提醒、停在追问、停在边界等收束方式。",
        ("结尾类型", "场景", "例句", "是否追问", "禁用条件"),
        ("所有聊天结尾", "低落", "问建议", "边界拒绝"),
    ),
    _lib(
        "language_information_order",
        "language_style",
        "信息顺序库",
        "保存情绪、事实、动作、判断、陪伴之间的排列顺序。",
        ("顺序", "场景", "核心意图", "例句", "稳定程度"),
        ("复杂回复", "建议", "冲突", "价值判断"),
    ),
    _lib(
        "language_turn_taking",
        "language_style",
        "话轮控制库",
        "保存会不会打断、拉回来、留空间、让用户继续说。",
        ("话轮策略", "触发场景", "追问方式", "停止条件", "反例"),
        ("多轮聊天", "用户沉默", "用户跑题", "危机对话"),
    ),
    _lib(
        "language_question_style",
        "language_style",
        "追问方式库",
        "保存温和追问、连续追问、不追问只陪着等方式。",
        ("追问模板", "追问强度", "场景", "上限", "禁用条件"),
        ("用户低落", "事实不清", "建议前澄清"),
    ),
    _lib(
        "language_phrase_templates",
        "language_style",
        "句式模板库",
        "保存可轻度泛化的稳定表达模板。",
        ("模板", "变量槽位", "原句", "使用场景", "复读风险"),
        ("高置信风格生成", "安抚", "提醒", "口吻控制"),
    ),
    _lib(
        "emotion_worry",
        "emotion_response",
        "担心反应库",
        "保存担心、不放心、安全提醒和风险规避反应。",
        ("触发点", "反应方式", "语言信号", "行动建议", "强度"),
        ("用户危险", "用户逞强", "用户晚归", "安全相关"),
    ),
    _lib(
        "emotion_anger",
        "emotion_response",
        "生气反应库",
        "保存愤怒、训斥、不满和语气变硬的反应。",
        ("触发点", "表达方式", "是否爆发", "修复方式", "底线"),
        ("用户犯错", "越界", "欺骗", "冲突"),
    ),
    _lib(
        "emotion_disappointment",
        "emotion_response",
        "失望反应库",
        "保存失望、冷下来、减少表达和关系受伤方式。",
        ("触发点", "表现", "语言变化", "恢复条件", "证据"),
        ("承诺破裂", "反复犯错", "信任问题"),
    ),
    _lib(
        "emotion_happiness",
        "emotion_response",
        "开心反应库",
        "保存开心、欣慰、玩笑和积极回应方式。",
        ("触发点", "表达方式", "强度", "身体/行动信号", "例句"),
        ("好消息", "日常分享", "被需要", "玩笑"),
    ),
    _lib(
        "emotion_tenderness",
        "emotion_response",
        "心疼反应库",
        "保存心疼、怜惜、放软、照顾和安抚反应。",
        ("触发点", "语言变化", "动作建议", "亲密距离", "强度"),
        ("用户低落", "生病", "疲惫", "逞强"),
    ),
    _lib(
        "emotion_grief",
        "emotion_response",
        "怀念与哀伤库",
        "保存怀念、失去、纪念和陪伴式回应边界。",
        ("触发点", "可说内容", "禁说内容", "安抚方式", "证据"),
        ("怀念", "失去", "纪念日", "用户想念 TA"),
    ),
    _lib(
        "emotion_anxiety",
        "emotion_response",
        "焦虑紧张库",
        "保存紧张、焦虑、反复确认和安全感需求。",
        ("触发点", "表现", "确认方式", "降温方式", "证据"),
        ("不确定风险", "等待结果", "关系不安"),
    ),
    _lib(
        "emotion_silence_cold",
        "emotion_response",
        "沉默冷处理库",
        "保存沉默、冷下来、少说话或回避表达的反应。",
        ("触发点", "沉默形态", "持续条件", "修复方式", "风险"),
        ("冲突", "被误解", "失望", "压力"),
    ),
    _lib(
        "personality_introversion",
        "personality_traits",
        "内外向倾向库",
        "保存外向/内向、表达主动性和社交能量。",
        ("倾向", "证据场景", "主动程度", "例外", "置信度"),
        ("关系距离判断", "日常聊天", "陌生场景"),
    ),
    _lib(
        "personality_rationality",
        "personality_traits",
        "理性感性库",
        "保存理性分析、情绪优先和判断依据偏好。",
        ("倾向", "判断依据", "情绪表达", "反例", "证据"),
        ("求建议", "价值判断", "冲突"),
    ),
    _lib(
        "personality_assertiveness",
        "personality_traits",
        "强势温和库",
        "保存强势、温和、直接、绕一点等稳定气质。",
        ("强度", "说话方式", "触发场景", "例句", "边界"),
        ("提醒", "冲突", "管束", "保护"),
    ),
    _lib(
        "personality_restraint",
        "personality_traits",
        "克制外露库",
        "保存情绪克制、表达外露和煽情边界。",
        ("克制程度", "表达强度", "失控场景", "反例", "证据"),
        ("低落安抚", "怀念", "冲突", "亲密表达"),
    ),
    _lib(
        "personality_sensitivity",
        "personality_traits",
        "敏感迟钝库",
        "保存对情绪、细节、态度变化的敏感程度。",
        ("敏感点", "察觉方式", "反应", "误判风险", "证据"),
        ("用户情绪变化", "关系不安", "冲突"),
    ),
    _lib(
        "personality_control_desire",
        "personality_traits",
        "控制感库",
        "保存安排动作、替人决定、管束和控制边界。",
        ("控制方式", "触发点", "语言信号", "可接受范围", "风险"),
        ("用户逞强", "建议", "冲突", "照顾"),
    ),
    _lib(
        "personality_protectiveness",
        "personality_traits",
        "保护欲库",
        "保存保护、担心、挡风险和替人扛事的倾向。",
        ("保护对象", "保护方式", "触发点", "强度", "证据"),
        ("危险", "低落", "家人/亲密关系"),
    ),
    _lib(
        "personality_responsibility",
        "personality_traits",
        "责任感库",
        "保存责任、承诺、照顾和必须做的事。",
        ("责任对象", "责任表达", "底线", "冲突", "证据"),
        ("家庭", "承诺", "工作", "照顾"),
    ),
    _lib(
        "values_family",
        "values_worldview",
        "家庭观库",
        "保存家庭、亲情、责任、照顾和牵挂的价值判断。",
        ("判断", "证据", "适用对象", "冲突", "禁用范围"),
        ("家庭话题", "亲人关系", "责任冲突"),
    ),
    _lib(
        "values_romance",
        "values_worldview",
        "感情观库",
        "保存亲密关系、陪伴、承诺、边界和依赖判断。",
        ("判断", "证据", "关系模式", "底线", "不确定性"),
        ("恋爱问题", "亲密表达", "关系冲突"),
    ),
    _lib(
        "values_money",
        "values_worldview",
        "金钱观库",
        "保存花钱、节俭、风险、借贷和经济责任判断。",
        ("判断", "偏好", "风险态度", "证据", "禁用建议"),
        ("金钱话题", "借钱", "消费", "风险选择"),
    ),
    _lib(
        "values_work",
        "values_worldview",
        "工作观库",
        "保存努力、效率、体面、成就和职业选择判断。",
        ("判断", "偏好", "底线", "压力反应", "证据"),
        ("工作求建议", "压力", "选择"),
    ),
    _lib(
        "values_morality",
        "values_worldview",
        "道德底线库",
        "保存欺骗、背叛、伤害、逃避等道德判断。",
        ("底线", "触发行为", "反应", "拒绝方式", "证据"),
        ("越界", "背叛", "欺骗", "价值判断"),
    ),
    _lib(
        "values_promise",
        "values_worldview",
        "承诺观库",
        "保存对承诺、守信、失约和长期责任的态度。",
        ("判断", "触发点", "失望反应", "修复条件", "证据"),
        ("承诺", "失约", "信任问题"),
    ),
    _lib(
        "values_freedom",
        "values_worldview",
        "自由边界观库",
        "保存自由、管束、尊重选择和不越界的判断。",
        ("判断", "允许范围", "控制边界", "冲突", "证据"),
        ("独立选择", "关系边界", "控制感"),
    ),
    _lib(
        "values_dignity",
        "values_worldview",
        "体面自尊库",
        "保存面子、尊严、自尊、被尊重和羞耻感。",
        ("触发点", "反应", "语言变化", "修复方式", "证据"),
        ("被否定", "被冒犯", "公开冲突"),
    ),
    _lib(
        "values_risk",
        "values_worldview",
        "风险偏好库",
        "保存保守、冒险、先安全还是先尝试的倾向。",
        ("风险态度", "判断顺序", "场景", "证据", "例外"),
        ("求建议", "危险", "选择"),
    ),
    _lib(
        "relationship_family_mode",
        "relationship_modes",
        "亲人关系模式库",
        "保存对亲人说话、照顾、管束和亲密距离。",
        ("关系对象", "表达方式", "距离", "管束程度", "证据"),
        ("亲人聊天", "家庭问题", "照顾提醒"),
    ),
    _lib(
        "relationship_friend_mode",
        "relationship_modes",
        "朋友关系模式库",
        "保存朋友之间的玩笑、支持、边界和距离。",
        ("关系对象", "表达方式", "幽默程度", "支持方式", "证据"),
        ("朋友话题", "轻松聊天", "求建议"),
    ),
    _lib(
        "relationship_romantic_mode",
        "relationship_modes",
        "恋人关系模式库",
        "保存恋人间的亲密表达、依赖、吃醋和边界。",
        ("亲密表达", "称呼", "边界", "冲突方式", "证据"),
        ("恋爱话题", "撒娇", "亲密冲突"),
    ),
    _lib(
        "relationship_distance",
        "relationship_modes",
        "亲密距离库",
        "保存不同关系下靠近、回避、管束和留空间的距离感。",
        ("关系", "距离", "靠近条件", "回避条件", "证据"),
        ("称呼", "安抚", "冲突", "越界检查"),
    ),
    _lib(
        "relationship_trust_pattern",
        "relationship_modes",
        "信任机制库",
        "保存什么会建立信任，什么会让 TA 失望或收回信任。",
        ("建立信任", "破坏信任", "修复条件", "反应", "证据"),
        ("承诺", "欺骗", "关系修复"),
    ),
    _lib(
        "relationship_exit_strategy",
        "relationship_modes",
        "关系退场策略库",
        "保存主动切断、告别、让对方放下、避免成为阻碍、以减少伤害为理由离开的关系策略。",
        ("退场触发", "离开理由", "对对方的期待", "减少伤害策略", "证据"),
        ("分手", "离开", "告别", "放下", "关系结束"),
    ),
    _lib(
        "decision_protect_vs_reason",
        "decision_logic",
        "保护优先/道理优先库",
        "保存遇事先保护人还是先讲道理的判断顺序。",
        ("优先级", "场景", "例句", "例外", "证据"),
        ("危险", "求建议", "冲突"),
    ),
    _lib(
        "decision_solve_vs_comfort",
        "decision_logic",
        "解决问题/安抚优先库",
        "保存先解决问题还是先安抚情绪的决策偏好。",
        ("优先级", "场景", "动作", "话术", "证据"),
        ("低落", "求建议", "危机"),
    ),
    _lib(
        "decision_fact_vs_relationship",
        "decision_logic",
        "事实/关系优先库",
        "保存判断时更看事实、原则还是关系感受。",
        ("优先级", "证据", "冲突", "降级条件", "例句"),
        ("价值判断", "关系冲突", "事实争议"),
    ),
    _lib(
        "decision_risk_style",
        "decision_logic",
        "风险决策库",
        "保存保守、冒险、先验证、先行动等决策模式。",
        ("风险类型", "判断方式", "行动建议", "证据", "限制"),
        ("风险选择", "工作", "金钱", "安全"),
    ),
    _lib(
        "decision_compromise_style",
        "decision_logic",
        "让步坚持库",
        "保存冲突中让步、坚持、拖延或折中的倾向。",
        ("倾向", "触发条件", "语言信号", "底线", "证据"),
        ("冲突", "谈判", "关系修复"),
    ),
    _lib(
        "conflict_silence",
        "conflict_defense",
        "沉默反应库",
        "保存被冒犯、失望、压力下是否沉默和怎么沉默。",
        ("触发点", "沉默时长", "语言减少", "修复方式", "证据"),
        ("冲突", "误解", "失望"),
    ),
    _lib(
        "conflict_reasoning",
        "conflict_defense",
        "讲道理反应库",
        "保存冲突时解释、摆事实、讲原则的方式。",
        ("触发点", "论证方式", "语气", "结尾", "证据"),
        ("冲突", "求判断", "犯错"),
    ),
    _lib(
        "conflict_outburst",
        "conflict_defense",
        "爆发反应库",
        "保存被触到底线时的爆发、训斥或强烈拒绝。",
        ("触发点", "爆发形式", "语言强度", "恢复条件", "证据"),
        ("底线被触碰", "危险", "背叛"),
    ),
    _lib(
        "conflict_repair",
        "conflict_defense",
        "误解修复库",
        "保存被误解后解释、道歉、退让或继续坚持的方式。",
        ("误解类型", "修复动作", "语言", "失败条件", "证据"),
        ("关系修复", "误会", "道歉"),
    ),
    _lib(
        "care_verbal_comfort",
        "care_companionship",
        "语言安慰库",
        "保存用话语安抚、确认情绪和稳定对方的方式。",
        ("安慰话术", "场景", "强度", "禁用表达", "证据"),
        ("低落", "怀念", "焦虑"),
    ),
    _lib(
        "care_action_based",
        "care_companionship",
        "行动照顾库",
        "保存通过喝水、休息、吃饭、到家报平安等动作表达关心。",
        ("动作", "触发场景", "语气", "顺序", "证据"),
        ("疲惫", "生病", "逞强", "日常提醒"),
    ),
    _lib(
        "care_control_reminder",
        "care_companionship",
        "管束提醒库",
        "保存带命令感、唠叨感或保护感的提醒。",
        ("提醒方式", "强度", "对象", "边界", "证据"),
        ("逞强", "危险", "作息", "健康"),
    ),
    _lib(
        "care_quiet_company",
        "care_companionship",
        "默默陪伴库",
        "保存少说、陪着、听着、不急着解决的陪伴方式。",
        ("陪伴方式", "语言量", "场景", "停止条件", "证据"),
        ("低落", "沉默", "怀念"),
    ),
    _lib(
        "care_problem_solving",
        "care_companionship",
        "解决问题式关心库",
        "保存把关心转化为步骤、建议、资源或行动安排。",
        ("问题类型", "步骤", "语气", "限制", "证据"),
        ("求建议", "工作压力", "现实问题"),
    ),
    _lib(
        "scenario_user_sad",
        "scenario_response",
        "用户低落场景库",
        "保存用户低落、难过、疲惫时的场景响应策略。",
        ("触发语", "情绪库", "关心方式", "语言风格", "边界"),
        ("用户说累", "用户不开心", "情绪低落"),
    ),
    _lib(
        "scenario_user_stubborn",
        "scenario_response",
        "用户逞强场景库",
        "保存用户硬撑、逞强、不休息时的制止和照顾策略。",
        ("触发语", "制止力度", "动作建议", "语言模板", "边界"),
        ("逞强", "硬撑", "不休息", "危险"),
    ),
    _lib(
        "scenario_user_advice",
        "scenario_response",
        "用户求建议场景库",
        "保存用户求建议时先问清、先安抚或直接给结论的策略。",
        ("问题类型", "判断库", "追问", "回复结构", "禁用建议"),
        ("求建议", "选择困难", "价值判断"),
    ),
    _lib(
        "scenario_user_mistake",
        "scenario_response",
        "用户犯错场景库",
        "保存用户犯错时训斥、安抚、讲道理或修复建议。",
        ("错误类型", "态度", "语气", "修复步骤", "底线"),
        ("犯错", "道歉", "后悔"),
    ),
    _lib(
        "scenario_user_silent",
        "scenario_response",
        "用户沉默场景库",
        "保存用户不说话、回避、停顿时的追问和留空间方式。",
        ("沉默信号", "追问方式", "等待方式", "禁用行为", "证据"),
        ("沉默", "不想说", "冷淡"),
    ),
    _lib(
        "scenario_user_jokes",
        "scenario_response",
        "用户玩笑场景库",
        "保存是否接玩笑、玩笑强度和不该开玩笑的话题。",
        ("玩笑类型", "接梗方式", "强度", "禁区", "证据"),
        ("玩笑", "调侃", "轻松聊天"),
    ),
    _lib(
        "scenario_user_misses_person",
        "scenario_response",
        "用户怀念 TA 场景库",
        "保存用户怀念目标人物时的陪伴和身份边界策略。",
        ("触发语", "可说内容", "禁说内容", "安抚方式", "现实支持"),
        ("想你", "怀念", "如果你还在", "失去"),
    ),
    _lib(
        "scenario_boundary_request",
        "scenario_response",
        "越界请求场景库",
        "保存用户要求冒充本人、编经历或越过安全边界时的拒绝策略。",
        ("越界类型", "拒绝方式", "替代回应", "语气", "记录"),
        ("冒充本人", "编事实", "危险建议", "越界"),
    ),
    _lib(
        "scenario_fact_question",
        "scenario_response",
        "事实问答场景库",
        "保存用户问事实时的证据检索、确认和不确定表达策略。",
        ("事实类型", "可引用证据", "不确定表达", "禁用推测", "证据"),
        ("问事实", "问经历", "问记忆"),
    ),
    _lib(
        "scenario_value_judgment",
        "scenario_response",
        "价值判断场景库",
        "保存用户要求 TA 判断一件事时需要检索的三观和决策库。",
        ("问题类型", "相关三观", "判断强度", "不确定表达", "边界"),
        ("该不该", "怎么看", "值不值得", "对不对"),
    ),
    _lib(
        "scenario_user_danger",
        "scenario_response",
        "危险场景库",
        "保存自伤、现实危险、医疗法律金融风险等高风险处理策略。",
        ("危险类型", "本地保护", "现实求助", "禁用内容", "降级规则"),
        ("自伤", "危险", "医疗", "法律", "金融"),
        prompt_budget=320,
    ),
    _lib(
        "growth_period_change",
        "growth_change",
        "时期变化库",
        "保存年轻时/后来/某段经历前后的人格和表达变化。",
        ("时期", "变化前", "变化后", "触发事件", "证据"),
        ("时间线", "成长变化", "资料来自不同阶段"),
    ),
    _lib(
        "growth_topic_sensitivity",
        "growth_change",
        "敏感话题变化库",
        "保存某些话题随经历变化而变得更敏感或更淡。",
        ("话题", "变化", "触发经历", "当前阶段", "证据"),
        ("敏感话题", "成长变化", "冲突"),
    ),
    _lib(
        "growth_relationship_change",
        "growth_change",
        "关系亲近变化库",
        "保存关系变近或变远后语言、边界和关心方式变化。",
        ("关系阶段", "变化", "触发点", "证据", "适用范围"),
        ("关系变化", "亲密距离", "称呼变化"),
    ),
    _lib(
        "boundary_impersonation",
        "boundary_confidence",
        "身份冒充边界库",
        "保存不能声称自己是本人、复活、有意识等硬边界。",
        ("禁止内容", "触发语", "拒绝模板", "替代回应", "记录"),
        ("你是不是本人", "复活", "冒充", "身份要求"),
        prompt_budget=320,
    ),
    _lib(
        "boundary_fact_invention",
        "boundary_confidence",
        "事实编造边界库",
        "保存不能编造经历、关系、承诺和未提供事实的规则。",
        ("禁止内容", "事实缺口", "不确定表达", "替代提问", "记录"),
        ("事实问答", "共同经历", "用户要求编造"),
        prompt_budget=320,
    ),
    _lib(
        "boundary_low_sample",
        "boundary_confidence",
        "低样本降级库",
        "保存低证据量时只能轻度借鉴、不能强模拟的规则。",
        ("等级", "限制", "允许范围", "禁用范围", "升级条件"),
        ("L0", "L1", "L2", "低证据", "不确定"),
        prompt_budget=260,
    ),
    _lib(
        "boundary_conflicting_evidence",
        "boundary_confidence",
        "冲突证据库",
        "保存证据冲突时降低置信、不强行统一人格的规则。",
        ("冲突点", "来源", "处理方式", "降级策略", "待确认项"),
        ("冲突资料", "多时期", "判断不一致"),
    ),
    _lib(
        "boundary_intimacy_overreach",
        "boundary_confidence",
        "亲密越界库",
        "保存不能凭空新增昵称、承诺、恋爱语气或强亲密表达的规则。",
        ("越界类型", "触发语", "降级表达", "禁用词", "证据要求"),
        ("亲密称呼", "恋人语气", "承诺", "低样本"),
    ),
    _lib(
        "boundary_mechanical_repetition",
        "boundary_confidence",
        "机械复读边界库",
        "保存不能把口头禅、语气词和模板机械重复的规则。",
        ("风险词", "重复上限", "替代表达", "触发场景", "检测方式"),
        ("口头禅", "语气词", "像一点", "高频重复"),
    ),
    _lib(
        "boundary_supported_scope",
        "boundary_confidence",
        "高置信可模拟范围库",
        "保存哪些画像层已有足够证据，可以进入高置信模拟。",
        ("可模拟范围", "证据数量", "覆盖场景", "限制", "升级条件"),
        ("高置信聊天", "用户要求真正像", "导出 skill"),
        prompt_budget=280,
    ),
)


PERSONA_LIBRARY_DEFINITIONS: dict[str, PersonaLibraryDefinition] = {
    definition.key: definition for definition in PERSONA_LIBRARY_REGISTRY
}

if len(PERSONA_LIBRARY_DEFINITIONS) != len(PERSONA_LIBRARY_REGISTRY):
    raise RuntimeError("Duplicate persona library keys in PERSONA_LIBRARY_REGISTRY")


def get_persona_library(key: str) -> PersonaLibraryDefinition | None:
    return PERSONA_LIBRARY_DEFINITIONS.get(key)


def list_persona_libraries() -> list[PersonaLibraryDefinition]:
    return list(PERSONA_LIBRARY_REGISTRY)


def get_persona_libraries_by_category() -> dict[str, list[PersonaLibraryDefinition]]:
    grouped: dict[str, list[PersonaLibraryDefinition]] = {}
    for definition in PERSONA_LIBRARY_REGISTRY:
        grouped.setdefault(definition.category, []).append(definition)
    return grouped
